# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-03 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item',
            field=models.CharField(choices=[('HDC', 'Heavy Duty Cuplock'), ('AL', 'Aluminium'), ('CRC', 'Core Cutting'), ('CTC', 'Concrete Cutting'), ('SF', 'Scaffolding')], max_length=3, null=True),
        ),
    ]
