# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-03 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quote', '0002_item_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='hiring_days',
            field=models.IntegerField(default=1),
        ),
    ]
